---
title: "Spezifische Zielgruppen"
output: html_notebook
---

```{r}
source("https://raw.githubusercontent.com/franciscowilhelm/r-collection/master/scoreItemsMulti.R")
```

Education Levels nach ecoplan Befragung (es gibt auch die OTP Version).

```{r}
scalenames <- c("oe", "jmk", "ssk", "inv", "con", "cl", "cop", "os", "jcha", "scs", "net", "cexpl", "lear")
edlvls <- levels(df_brm$Ausb_recode2)
alpha_by_edu <- map_dfc(edlvls, function(edlvl) {
  df_brm %>%
    select(Ausb_recode2, oe1_work:lear3_work) %>% 
    filter(Ausb_recode2 == edlvl) %>% 
    scoreItemsMulti(scalenames, ., exclude = TRUE) %>% 
    .$alpha %>% .[1,] %>% enframe()
}) 

names(alpha_by_edu) <- c("Skala", edlvls)
alpha_by_edu$Skala <- c("Berufliche Expertise", "Arbeitsmarktwissen", "Allgemeine Fähigkeiten", "Wichtigkeit der Arbeit",
                        "Zutrauen", "Klarheit", "Entwicklungsmöglichkeiten", "Organisationale Unterstützung",
                        "Arbeitsherausforderung", "Soziale Unterstützung", "Netzwerken", "Informieren über Möglichkeiten",
                        "Kontinuierliches Lernen")
alpha_by_edu %>% map(~min(.x)) # alpha mins increase by education, but its still adequate with lower level.
alpha_by_edu %>% map(~mean(.x)) 

alpha_by_edu %>% write.table(., "clipboard", sep="\t", row.names=FALSE)
```
Bildung Nach OTP:

```{r}
edlvls <- levels(df_crq$education_de)[-c(1,7)] #don't do it for obligatorisch and doktorat - not enough cases yet

alpha_by_edu <- map(edlvls, function(edlvl) {
  df_crq %>%
    select(education_de, oe1_work:lear3_work) %>% 
    filter(education_de == edlvl) %>% 
    scoreItemsMulti(scalenames, ., exclude = TRUE) %>% 
    .$alpha
}) 



alpha_by_edu %>% map(~min(.x)) # alpha mins increase by education, but its still adequate with lower level.
alpha_by_edu %>% map(~mean(.x)) 
```

Korrelation mit B1_AMF
```{r}
edlvls <- levels(df_brm$Ausb_recode2)
tmp <- map_dfr(edlvls, function(lvl) {
  df_brm %>% filter(Ausb_recode2 == lvl) %>% 
        lm(B1_amf ~ oe  +  jmk  +  ssk  +  inv  +  con  +  cl  +  cop  +  os  +  jcha  +  scs  +  net  +  cexpl  +  lear,
   .) %>% glance() %>% mutate(edu = lvl)
  })

tmp %>% mutate(mcorr = sqrt(r.squared)) %>% write.table(., "clipboard", sep="\t", row.names=FALSE)
```

Z-standardisiert B1_AMF, dann Differenz nach Bildung?
```{r}
df_brm %>% mutate(B1_amf_z  = scale(B1_amf)) %>% group_by(Ausb_recode2) %>% summarise(across(c(knsk, mot, env, act, B1_amf), ~mean(.x, na.rm = TRUE)))

```



```{r}
df_brm %>% filter(A1_GruendeSQ002 == "Ja") %>% 
      lm(B1_amf ~ oe  +  jmk  +  ssk  +  inv  +  con  +  cl  +  cop  +  os  +  jcha  +  scs  +  net  +  cexpl  +  lear,
 .) %>% glance()

df_brm %>% filter(A1_GruendeSQ001 == "Ja") %>% 
      lm(B1_amf ~ oe  +  jmk  +  ssk  +  inv  +  con  +  cl  +  cop  +  os  +  jcha  +  scs  +  net  +  cexpl  +  lear,
 .) %>% glance()
```